# Generated by Django 4.2 on 2026-04-14 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(default='Anonymous', max_length=100)),
                ('scan_type', models.CharField(choices=[('Brain', 'Brain MRI'), ('Bone', 'Bone X-ray'), ('Chest', 'Chest X-ray')], max_length=50)),
                ('prediction', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('image_path', models.CharField(max_length=255)),
                ('report_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
