# Generated by Django 4.2 on 2026-04-17 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_patientreport_scan_delete_scanrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('license_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Admin', 'Hospital Admin')], default='Patient', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PatientReport',
        ),
        migrations.AddField(
            model_name='scan',
            name='approval_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scan',
            name='boxed_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scan',
            name='clinical_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='doctor_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='scan',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scan',
            name='measurements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('AI_COMPLETED', 'AI Assessment Done'), ('PENDING_REVIEW', 'Doctor Review Pending'), ('APPROVED', 'Verified by Doctor'), ('CRITICAL', 'Emergency Alert!')], default='AI_COMPLETED', max_length=20),
        ),
        migrations.AlterField(
            model_name='scan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scan',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hospital'),
        ),
    ]
