# Generated by Django 4.2 on 2026-04-17 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_hospital_userprofile_delete_patientreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('digital_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('hospital_seal', models.ImageField(blank=True, null=True, upload_to='seals/')),
                ('confidence_threshold', models.IntegerField(default=85)),
                ('auto_approve_low_risk', models.BooleanField(default=False)),
                ('show_heatmap', models.BooleanField(default=True)),
                ('show_probability_scores', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=True)),
                ('emergency_active', models.BooleanField(default=True)),
                ('consultation_hours', models.CharField(default='09:00 AM - 05:00 PM', max_length=100)),
                ('dark_mode', models.BooleanField(default=True)),
                ('compact_view', models.BooleanField(default=False)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
