# Generated by Django 4.2 on 2026-04-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_prescriptiontemplate_doctorsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorsettings',
            name='show_probability_scores',
        ),
        migrations.AddField(
            model_name='doctorsettings',
            name='accent_color',
            field=models.CharField(default='#00f2ff', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorsettings',
            name='allow_reupload',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctorsettings',
            name='auto_archive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctorsettings',
            name='consultation_charge',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctorsettings',
            name='data_encryption',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctorsettings',
            name='follow_up_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='doctorsettings',
            name='font_size',
            field=models.CharField(default='Normal', max_length=10),
        ),
        migrations.AddField(
            model_name='doctorsettings',
            name='payout_method',
            field=models.CharField(default='Bank Transfer', max_length=50),
        ),
        migrations.AddField(
            model_name='doctorsettings',
            name='qr_verification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctorsettings',
            name='session_timeout',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='doctorsettings',
            name='share_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctorsettings',
            name='two_factor_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorsettings',
            name='vacation_mode',
            field=models.BooleanField(default=False),
        ),
    ]
