# Generated by Django 4.2 on 2026-04-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_doctorsettings_show_probability_scores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='boxed_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='heatmap_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
